apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: studentqna
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
